"""empty message

Revision ID: 00adbbe860b5
Revises: 66d215bc69c3
Create Date: 2023-12-24 15:20:32.012192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00adbbe860b5'
down_revision = '66d215bc69c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
