"""empty message

Revision ID: 4bf3e4776738
Revises: 
Create Date: 2023-11-16 01:07:13.690638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf3e4776738'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batteries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voltage', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('capacity', sa.String(), nullable=False),
    sa.Column('configuration', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('controllers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('features', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('length', sa.String(), nullable=False),
    sa.Column('material', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('max_speeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('speed', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('motors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('kv', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('range', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('remotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('features', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('trucks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('width', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('wheels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.Column('wheel_id', sa.Integer(), nullable=True),
    sa.Column('truck_id', sa.Integer(), nullable=True),
    sa.Column('motor_id', sa.Integer(), nullable=True),
    sa.Column('battery_id', sa.Integer(), nullable=True),
    sa.Column('controller_id', sa.Integer(), nullable=True),
    sa.Column('remote_id', sa.Integer(), nullable=True),
    sa.Column('max_speed_id', sa.Integer(), nullable=True),
    sa.Column('range_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['battery_id'], ['batteries.id'], name=op.f('fk_boards_battery_id_batteries')),
    sa.ForeignKeyConstraint(['controller_id'], ['controllers.id'], name=op.f('fk_boards_controller_id_controllers')),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], name=op.f('fk_boards_deck_id_decks')),
    sa.ForeignKeyConstraint(['max_speed_id'], ['max_speeds.id'], name=op.f('fk_boards_max_speed_id_max_speeds')),
    sa.ForeignKeyConstraint(['motor_id'], ['motors.id'], name=op.f('fk_boards_motor_id_motors')),
    sa.ForeignKeyConstraint(['range_id'], ['ranges.id'], name=op.f('fk_boards_range_id_ranges')),
    sa.ForeignKeyConstraint(['remote_id'], ['remotes.id'], name=op.f('fk_boards_remote_id_remotes')),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], name=op.f('fk_boards_truck_id_trucks')),
    sa.ForeignKeyConstraint(['wheel_id'], ['wheels.id'], name=op.f('fk_boards_wheel_id_wheels')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boards')
    op.drop_table('wheels')
    op.drop_table('trucks')
    op.drop_table('remotes')
    op.drop_table('ranges')
    op.drop_table('motors')
    op.drop_table('max_speeds')
    op.drop_table('decks')
    op.drop_table('controllers')
    op.drop_table('batteries')
    # ### end Alembic commands ###
