"""empty message

Revision ID: 4c7fcbd2a6bd
Revises: d2388715f7ae
Create Date: 2024-01-02 23:43:52.521680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7fcbd2a6bd'
down_revision = 'd2388715f7ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hearts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gallery_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['gallery.id'], name=op.f('fk_hearts_gallery_id_gallery')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_hearts_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'gallery_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hearts')
    # ### end Alembic commands ###
