"""empty message

Revision ID: 633612465282
Revises: f796349e3d69
Create Date: 2024-02-29 17:53:29.167790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633612465282'
down_revision = 'f796349e3d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.alter_column('image_filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('deck_brand',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('deck_size',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('battery_series',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('battery_parallel',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('motor_size',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('motor_kv',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('motor_power',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('wheel_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('wheel_size',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('max_speed',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('max_range',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('other_features',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.alter_column('other_features',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('max_range',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('max_speed',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('wheel_size',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('wheel_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('motor_power',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('motor_kv',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('motor_size',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('battery_parallel',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('battery_series',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('deck_size',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('deck_brand',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('image_filename',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
