"""empty message

Revision ID: 701c62d440d7
Revises: c90f62359952
Create Date: 2024-01-03 18:56:38.104850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701c62d440d7'
down_revision = 'c90f62359952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.drop_column('hearts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hearts', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
