"""empty message

Revision ID: 714656b214b5
Revises: b4e0668f44b5
Create Date: 2024-01-10 18:04:52.281867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714656b214b5'
down_revision = 'b4e0668f44b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_contacts_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_contacts_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
