"""empty message

Revision ID: 7165db8da8bc
Revises: bc66c09c57ff
Create Date: 2023-11-29 02:12:08.610894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7165db8da8bc'
down_revision = 'bc66c09c57ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
