"""empty message

Revision ID: 7400a86d2aa8
Revises: 4c7fcbd2a6bd
Create Date: 2024-01-02 23:50:44.631957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7400a86d2aa8'
down_revision = '4c7fcbd2a6bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hearts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.drop_column('hearts')

    # ### end Alembic commands ###
