"""empty message

Revision ID: 7873613570a5
Revises: 
Create Date: 2024-01-02 02:42:39.103885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7873613570a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(), nullable=False),
    sa.Column('battery_type', sa.String(), nullable=False),
    sa.Column('motor_type', sa.String(), nullable=False),
    sa.Column('wheel_type', sa.String(), nullable=False),
    sa.Column('gear_ratio', sa.String(), nullable=False),
    sa.Column('max_speed', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('fname', sa.String(), nullable=False),
    sa.Column('lname', sa.String(), nullable=False),
    sa.Column('rider_stance', sa.String(), nullable=False),
    sa.Column('boards_owned', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_type', sa.String(), nullable=False),
    sa.Column('deck_length', sa.String(), nullable=False),
    sa.Column('deck_material', sa.String(), nullable=False),
    sa.Column('truck_type', sa.String(), nullable=False),
    sa.Column('truck_width', sa.String(), nullable=False),
    sa.Column('controller_feature', sa.String(), nullable=False),
    sa.Column('controller_type', sa.String(), nullable=False),
    sa.Column('remote_feature', sa.String(), nullable=False),
    sa.Column('remote_type', sa.String(), nullable=False),
    sa.Column('motor_size', sa.String(), nullable=False),
    sa.Column('motor_kv', sa.String(), nullable=False),
    sa.Column('wheel_size', sa.String(), nullable=False),
    sa.Column('wheel_type', sa.String(), nullable=False),
    sa.Column('battery_voltage', sa.String(), nullable=False),
    sa.Column('battery_type', sa.String(), nullable=False),
    sa.Column('battery_capacity', sa.String(), nullable=False),
    sa.Column('battery_configuration', sa.String(), nullable=False),
    sa.Column('range_mileage', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_boards_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('gurus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_input', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_gurus_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('qna',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post', sa.String(), nullable=False),
    sa.Column('reply', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_qna_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reply', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('qna_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['qna_id'], ['qna.id'], name=op.f('fk_replies_qna_id_qna')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replies')
    op.drop_table('qna')
    op.drop_table('gurus')
    op.drop_table('boards')
    op.drop_table('users')
    op.drop_table('gallery')
    op.drop_table('contacts')
    # ### end Alembic commands ###
