"""empty message

Revision ID: ab4dcd89760d
Revises: bac490dd6435
Create Date: 2024-01-08 06:19:42.148133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab4dcd89760d'
down_revision = 'bac490dd6435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('hearts', schema=None) as batch_op:
        batch_op.alter_column('gallery_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hearts', schema=None) as batch_op:
        batch_op.alter_column('gallery_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
