"""empty message

Revision ID: d2388715f7ae
Revises: 7873613570a5
Create Date: 2024-01-02 03:16:06.709450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2388715f7ae'
down_revision = '7873613570a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('truck_type', sa.String(), nullable=False))
        batch_op.drop_column('gear_ratio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gear_ratio', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('truck_type')

    # ### end Alembic commands ###
