"""empty message

Revision ID: e08dcc8227c6
Revises: 72e45d191e4b
Create Date: 2023-12-31 04:13:01.806060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e08dcc8227c6'
down_revision = '72e45d191e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(), nullable=False),
    sa.Column('menu1', sa.String(), nullable=False),
    sa.Column('menu2', sa.String(), nullable=False),
    sa.Column('menu3', sa.String(), nullable=False),
    sa.Column('menu4', sa.String(), nullable=False),
    sa.Column('menu5', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gallery')
    # ### end Alembic commands ###
